add_newline = true
format = """
[](fg:#3B4252)\
$time\
$username\
[](bg:#ECEFF4 fg:#3B4252)\
$directory\
[](bg:#434C5E fg:#ECEFF4)\
$git_branch\
$git_metrics\
$git_status\
[](bg:#5e81ac fg:#434C5E)\
$kubernetes\
[](fg:#5e81ac)\
$all\
"""

[username]
show_always = true
style_user = "bg:#3B4252 fg:#E5E9F0"
style_root = "bg:#3B4252 fg:#BF616A"
format = '[ $user ]($style)'
disabled = false


[directory]
style = "bg:#ECEFF4 fg:#434C5E"
format = '[ $path]($style)'
truncation_length = 2
truncate_to_repo = true
truncation_symbol = ".../"

[git_branch]
style = "bg:#434C5E"
truncation_length = 10
symbol = ""
format = '[ $symbol $branch ]($style)'
disabled = false

[git_commit]
commit_hash_length = 5

[git_metrics]
disabled = false
added_style = "bg:#434C5E fg:#A3BE8C"
deleted_style = "bg:#434C5E fg:#BF616A"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[git_status]
modified = '~ '
ahead = '~$count'
style = 'bg:#434C5E'
diverged = '[$ahead_count $behind_count]($style)'

format = '[\[[$diverged](fg:#D08770 bg:#434C5E)\]]($style)'

[kubernetes]
style = "bg:#5e81ac"
symbol = 'ﴱ'
disabled = false
format = '[ $symbol $context]($style)'
[time]
style = "bg:#3B4252 fg:#E5E9F0"
disabled = false
format = '[$time]($style)'
